### ISSUE TITLE
Create helper function with hooks/filters for getting user wallet balance

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-wallet#2]
It'd be nice for extensions, integrations, and just general usages if the method of getting the customer's wallet value wasn't directly accessing post meta.

`get_user_meta( $user_id, '_edd_wallet_value', true );`

We should introduce something like `edd_wallet_get_user_balance( $user_id = 0 )` which could then have filters and other areas for integration.

**Comment by cklosowski** [comment]
The reasoning here is things like, the Manual Purchases update we're looking at is calling the usermeta directly, would be nice to have a central function for this data.

**Comment by ghost1227** [comment]
I'm working on improving this (and a few other things). Some of the repetitive stuff definitely needs to be handled better. I'm going to rework it to have a better API for working with user wallets so add/remove/check/etc can be done easily.

**Comment by pippinsplugins** [comment]
Should also have helpers for adding / subtracting from balance.

**Comment by cklosowski** [comment]
@pippinsplugins was just coming back for that part...the updating and adding of balances should be wrapped.

**Comment by mindctrl** [comment]
The [edd_wallet] shortcode should probably output the balance somewhere. It makes sense to know your existing balance before depositing more. At this time the only way I see to view your balance is add items to the cart and go to the checkout screen, and that's only if the option is enabled.

**Comment by ghost1227** [comment]
@mindctrl The latest version I've added an [edd_wallet_balance] shortcode
