### ISSUE TITLE
"The selected payment gateway is not enabled" when only one gateway enabled

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-wallet#20]
Talked with Dan about this in Slack. I've seen two reports of this now.

When only one gateway (besides Wallet) is enabled, you can't add funds to the Wallet. The error on the checkout page is `Error: The selected payment gateway is not enabled`.

To replicate:
- Enable Wallet and one other gateway.
![image](https://cloud.githubusercontent.com/assets/1254870/11614736/34b10e6a-9c19-11e5-8e19-6e039c58b43f.png)
- Go to page with `[edd_wallet]` shortcode, select an amount, and proceed to checkout
- Try to complete purchase

You get this:
![image](https://cloud.githubusercontent.com/assets/1254870/11614743/5f9a2e5e-9c19-11e5-9dd2-3f2b9b619840.png)

Reported [here](https://secure.helpscout.net/conversation/146323541/22848/?folderId=180499) and [here](https://secure.helpscout.net/conversation/140571932/21608/?folderId=386431).

**Comment by pippinsplugins** [comment]
[This ticket](https://secure.helpscout.net/conversation/146323541/22848/?folderId=180504) doesn't have Wallet enabled as a gateway. Could still be related just noting it in case it matters.

**Comment by SDavisMedia** [comment]
Make that 3 reports. And I was able to replicate. https://secure.helpscout.net/conversation/143549133/22291/?folderId=321418 

@ghost1227 Got a plan for fixing this?

**Comment by pippinsplugins** [comment]
I'm trying to fix this now but currently can't replicate it.

**Comment by pippinsplugins** [comment]
Ah, looks like it might only happen when not using `Test Payment`.

**Comment by pippinsplugins** [comment]
I also got this notice just now:

Warning: Invalid argument supplied for foreach() in /Users/pippinwilliamson/Sites/trunk/wp-content/plugins/easy-digital-downloads/includes/gateways/paypal-standard.php on line 111

**Comment by pippinsplugins** [comment]
Ah, ^ is an EDD core bug I think.

**Comment by pippinsplugins** [comment]
I still can't replicate this . . . I've tried with Test Payment, Stripe, and PayPal.

**Comment by pippinsplugins** [comment]
Note, if you see a statement_descriptor error when testing this with Stripe, see https://github.com/easydigitaldownloads/edd-stripe/issues/66

**Comment by pippinsplugins** [comment]
I've tested on both EDD `master` and `release/2.5`. Neither trigger the error for me.

**Comment by pippinsplugins** [comment]
Apparently this was fixed in https://github.com/easydigitaldownloads/edd-wallet/commit/7f24f68cf28296ddbcc9b3be220b7c09a8e08304

@ghost1227 PLEASE make sure you have an issue created for EVERY commit. John and I just spent an hour plus trying to track this down only to find it was already fixed. We've had customers waiting on this for a week plus. Discovering that it was fixed more than two weeks ago but without any notice to the team is painful.
