### ISSUE TITLE
Add PHP version check to prevent fatal error on PHP 5.2

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-wallet#21]
On PHP 5.2, activating the plugin causes a fatal error:
`PHP Parse error:  syntax error, unexpected T_FUNCTION in /wp-content/plugins/edd-wallet/includes/functions.php on line 57`

We list 5.3 or greater in requirements, but preventing the fail and maybe adding a notice would be nice.

**Comment by ghost1227** [comment]
...I don't think that function is even used anymore...
