### ISSUE TITLE
Incentives aren't automatically applied if Wallet is the default gateway

### ISSUE THREAD

**Issue by mindctrl** [easydigitaldownloads/edd-wallet#24]
They're only applied on switch. If Wallet is the default, they won't show up unless you switch to another gateway and then back to Wallet.

[Reported here](https://secure.helpscout.net/conversation/151006181/23715/?folderId=180499) and confirmed locally.

**Comment by ghost1227** [comment]
Starting with `release/2.0.0` Wallet isn't a true gateway anymore, which makes this no longer relevant.
