### ISSUE TITLE
edd_wallet_value_shortcode is using get_currentuserinfo

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-wallet#26]
The shortcode `[edd_wallet_value_shortcode]` is using the function `get_currentuserinfo()` which throws deprecated notices when running trunk.

`Notice: get_currentuserinfo is <strong>deprecated</strong> since version 4.5! Use wp_get_current_user()`

**Comment by pippinsplugins** [comment]
@ghost1227
