### ISSUE TITLE
Plugin does not check if EDD is enabled

### ISSUE THREAD

**Issue by jamesgol** [easydigitaldownloads/edd-wallet#3]
Disabled EDD in WordPress without disabling edd-wallet and got an error
Fatal error: Class 'EDD_DB' not found in /home/james/www/wordpress/wp-content/plugins/edd-wallet/includes/class.edd-db-wallet.php on line 21

**Comment by ghost1227** [comment]
@pippinsplugins I'm not quite sure how to handle this without either automatically deactivating if EDD isn't available (which we don't want) or wrapping every single function that uses EDD in a class_exists check (which would get rediculous).

**Comment by jamesgol** [comment]
Seems like the common method in this situation is just to return without doing anything and possibly display a notice on admin pages

**Comment by mindctrl** [comment]
This was fixed in https://github.com/easydigitaldownloads/edd-wallet/commit/ec137722379db507111be346a7e30c7f39a8e2db
