### ISSUE TITLE
Checkout page gateway label modified too early

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-wallet#32]
When selecting to display the Wallet total in the gateway label on the checkout page, we run into the following error:

```
Notice: is_page was called incorrectly. Conditional query tags do not work before the query is run. Before then, they always return false. Please see Debugging in WordPress for more information. (This message was added in version 3.1.) in /Applications/MAMP/htdocs/localhost/sandhills/wp-includes/functions.php on line 3897
```

The label is being modified when the gateway is registered, which is too early. A filter is being added to EDD core and Wallet will need to use that instead. https://github.com/easydigitaldownloads/easy-digital-downloads/issues/4816

**Comment by cklosowski** [comment]
Requires EDD 2.6.5 (current in `issue/4816` but soon in the release).
