### ISSUE TITLE
PHP: Fatal error: Class 'EDD_DB' not found

### ISSUE THREAD

**Issue by bossman28** [easydigitaldownloads/edd-wallet#43]
I've tried everything I know to fix this issue and ive hit a road block. Trying to activate the edd wallet plugin and im hit with: Plugin could not be activated because it triggered a fatal error. Fatal error: Class 'EDD_DB' not found in... /wp-content/plugins/edd-wallet/includes/class.edd-db-wallet.php on line 21. 

I've tried adding code that i seen you post on other post, nothing is working, deactivated all plugins that didnt work either. 

thank in advance for any help

**Comment by pippinsplugins** [comment]
Do you have the main Easy Digital Downloads plugin activated?

**Comment by bossman28** [comment]
Yes I got everything to work except I can't figure out how to show the available store credit balance on the affiliates statistics dashboard. The short code edd_wallet_value only shows the total commission earned

**Comment by pippinsplugins** [comment]
Hi there!

Please go ahead and open a support ticket through our support portal: https://easydigitaldownloads.com/support

we use GitHub for development tracking only.
