### ISSUE TITLE
Add widget that shows wallet balance for logged in customer

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-wallet#8]
Adam Pickering has requested a widget that shows a logged-in customer their balance and wallet details:

>>>@dgriffiths: just a suggestion for your EDD Wallet add-on, displaying the amount that the user has in their wallet on the deposit page and the checkout is great!! but what would be great is to add a menu item or widget that displays the same information so that the site admin can add it to their menu or widget area, so it's super quick to see how much you have in your EDD wallet.

>>>If you can already do this let us know as we want to promote this add-on in Marketify 2.0 theme release

I agree.

**Comment by SDavisMedia** [comment]
It would also be nice if there was a shortcode for it. :+1:

**Comment by SDavisMedia** [comment]
Never mind. I see `[edd_wallet_value]` is already in place. Not sure if it's done or not, though.

**Comment by ghost1227** [comment]
@pippinsplugins @SDavisMedia Assuming I was to add a menu item or widget for it... what should it look like? Just a widget showing the value seems like a lot of wasted space... (technically, you could put the shortcode into a text widget though...)

**Comment by pippinsplugins** [comment]
Identical to the currently shortcode, just in widget form.
