### ISSUE TITLE
Getting error on loading 

### ISSUE THREAD

**Issue by luzram** [easydigitaldownloads/edd-wallet#9]
Hey Guys, I was testing the plugin before buying the licence, and I get this error on the console:

../wp-content/plugins/edd-wallet-master/assets/js/edd-wallet-incentives.min.js?ver=1.0.4 Failed to load resource: the server responded with a status of 404 (Not Found)

I've noticed that "edd-wallet-incentives.min.js" does not exists... there's a edd-wallet-incentives.js, but not the min.... 

I haven't tested the functionality yet... so I'm not sure of how important this error is... but just so you know.

**Comment by ghost1227** [comment]
Fixed with https://github.com/easydigitaldownloads/edd-wallet/commit/d2fbd1a1f0b5437fdfe7350c1ec5d607f270165c
